### ISSUE TITLE
Can't run the tests file

### ISSUE THREAD

**Issue by williamchristianc** [lvorspel/DiGriPy#2]
Hi,
thanks for creating this amazing tool, but I have an issue for running it. Even though I already followed the steps and use the python 3.8. Here is the issue:
 python -m digripy.run -i tests/example80C -l 20
WARNING:root:Disabled multi-processing.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Lib\site-packages\digripy\run.py", line 77, in <module>
    tespy.logger.define_logging(log_path=True, log_version=True,      
TypeError: define_logging() got an unexpected keyword argument 'log_path'

**Comment by fwitte** [comment]
Hi @williamchristianc,

I am the developer of tespy, which this library builds on. By chance stubled over this... Due to larger changes and restructuring of tespy, some features of this package might be broken... You could try it with tespy version 0.6.2 or lower ;)

Best

**Comment by SalehCheikh** [comment]
Hi @fwitte,
I have an issue when running it. Despite following the steps, here is the issue :

python -m digripy.run -i tests/example80C -l 20

WARNING:root:Disabled multi-processing.
Traceback (most recent call last):
  File "", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "", line 87, in _run_code
    exec(code, run_globals)
  File "..\lib\site-packages\digripy\run.py", line 96, in <module>
    num_settings, settings = tools.read_settings_file(input_dir,
TypeError: cannot unpack non-iterable NoneType object

I first installed digripy using :
python -m pip install digripy

The TESPy version was 0.7.2, but I had the problem mentionned above. 
Then I downgraded TESPy to 0.6.2 and I have the current problem. 

Do you have any idea how to solve this please ?

**Comment by fwitte** [comment]
Hmmm, since I did not create this library and do not maintain it, I cannot really help here. Sorry for that! I have made quite a few changes to TESPy since the last update of this repo, so very likely things broke and have to be fixed. I do not have the capacities to do so right now unfortunately.

Best
